# Jekyll
permalink: pretty
paginate: 10 
name: ModelMapper
baseurl: 
markdown: kramdown
version: 2.1.1

kramdown:
  parse_block_html: true

kramdown:
  input: GFM
  enable_coderay: false
  syntax_highlighter_opts:
    disable : true
